// Code generated by "stringer -type=BaseType"; DO NOT EDIT.

package flect

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[String-1]
	_ = x[Bool-2]
	_ = x[Array-3]
	_ = x[U8-4]
	_ = x[U16-5]
	_ = x[U32-6]
	_ = x[U64-7]
	_ = x[Uint-8]
	_ = x[I8-9]
	_ = x[I16-10]
	_ = x[I32-11]
	_ = x[I64-12]
	_ = x[Int-13]
}

const _BaseType_name = "UnknownStringBoolArrayU8U16U32U64UintI8I16I32I64Int"

var _BaseType_index = [...]uint8{0, 7, 13, 17, 22, 24, 27, 30, 33, 37, 39, 42, 45, 48, 51}

func (i BaseType) String() string {
	if i >= BaseType(len(_BaseType_index)-1) {
		return "BaseType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BaseType_name[_BaseType_index[i]:_BaseType_index[i+1]]
}
